### PR TITLE
Added ed dependency to rosdep

### PR DESCRIPTION
**Pull request by pablogs9**
ed is merged into rosdep package list: https://github.com/ros/rosdistro/pull/23966

### CODE REVIEW

**Comment by iluetkeb** [comment]
The change looks good, but what's about with that "ros-dashing-launch-testing" failure?

**Comment by pablogs9** [comment]
@jfm92 can you tell us something about this CI failure?

**Comment by julibert** [comment]
Please @pablogs9, could rebase it over dashing?

**Comment by pablogs9** [comment]
Superseed by https://github.com/micro-ROS/micro-ros-build/pull/87

**Pull request closed without merging**
